/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faculty.project;
import DB.Departement;
import DB.Course;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mohamed
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        logOutAdmin = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCourseId = new javax.swing.JTextField();
        txtCourseDesc = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        boxCourseCredit = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAddCourse = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        boxCourseType = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDepId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDepName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDepNoOffice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnAddDep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Course.png"))); // NOI18N

        logOutAdmin.setBackground(new java.awt.Color(255, 255, 255));
        logOutAdmin.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        logOutAdmin.setForeground(new java.awt.Color(204, 0, 0));
        logOutAdmin.setText("LOG Out");
        logOutAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(logOutAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel11)
                .addGap(62, 62, 62)
                .addComponent(logOutAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("    Add Course");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id.png"))); // NOI18N

        txtCourseId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCourseId.setForeground(new java.awt.Color(153, 153, 153));
        txtCourseId.setText("Course ID....");
        txtCourseId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtCourseId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCourseIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCourseIdFocusLost(evt);
            }
        });

        txtCourseDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCourseDesc.setForeground(new java.awt.Color(153, 153, 153));
        txtCourseDesc.setText("Course Description...");
        txtCourseDesc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtCourseDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCourseDescFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCourseDescFocusLost(evt);
            }
        });

        txtCourseName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCourseName.setForeground(new java.awt.Color(153, 153, 153));
        txtCourseName.setText("Course Name....");
        txtCourseName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtCourseName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCourseNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCourseNameFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Credit....");

        boxCourseCredit.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        boxCourseCredit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));
        boxCourseCredit.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/description (1).png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/credit.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/description (1).png"))); // NOI18N

        btnAddCourse.setBackground(new java.awt.Color(204, 0, 0));
        btnAddCourse.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        btnAddCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCourse.setText("ADD");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("Course Type...");

        boxCourseType.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        boxCourseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Required", "Elective", " " }));
        boxCourseType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(txtCourseDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                .addComponent(txtCourseId)
                                .addComponent(txtCourseName)
                                .addComponent(boxCourseCredit, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(boxCourseType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCourseId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)))
                        .addGap(40, 40, 40)
                        .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCourseDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxCourseCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxCourseType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        jTabbedPane1.addTab("Courses", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 35)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("    Add Departement");

        txtDepId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDepId.setForeground(new java.awt.Color(153, 153, 153));
        txtDepId.setText("Departement ID....");
        txtDepId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtDepId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepIdFocusLost(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id.png"))); // NOI18N

        txtDepName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDepName.setForeground(new java.awt.Color(153, 153, 153));
        txtDepName.setText("Departement Name....");
        txtDepName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtDepName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepNameFocusLost(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/description (1).png"))); // NOI18N

        txtDepNoOffice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDepNoOffice.setForeground(new java.awt.Color(153, 153, 153));
        txtDepNoOffice.setText("Departement Office No.....");
        txtDepNoOffice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtDepNoOffice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepNoOfficeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepNoOfficeFocusLost(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/credit.png"))); // NOI18N

        btnAddDep.setBackground(new java.awt.Color(204, 0, 0));
        btnAddDep.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        btnAddDep.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDep.setText("ADD");
        btnAddDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(135, 135, 135)
                            .addComponent(jLabel3))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDepName, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(34, 34, 34)
                                    .addComponent(txtDepId, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDepNoOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnAddDep, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(txtDepId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDepName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txtDepNoOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnAddDep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        jTabbedPane1.addTab("Departements", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCourseIdFocusGained
        // TODO add your handling code here:
         if(txtCourseId.getText().equals("Course ID...."))
        {
            txtCourseId.setText("");
        }
        
    }//GEN-LAST:event_txtCourseIdFocusGained

    private void txtCourseIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCourseIdFocusLost
        // TODO add your handling code here:
        if(txtCourseId.getText().equals(""))
        {
            txtCourseId.setText("Course ID....");
        }
    }//GEN-LAST:event_txtCourseIdFocusLost

    private void txtCourseNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCourseNameFocusGained
        // TODO add your handling code here:
         if(txtCourseName.getText().equals("Course Name...."))
        {
            txtCourseName.setText("");
        }
    }//GEN-LAST:event_txtCourseNameFocusGained

    private void txtCourseNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCourseNameFocusLost
        // TODO add your handling code here:
        if(txtCourseName.getText().equals(""))
        {
            txtCourseName.setText("Course Name....");
        }
    }//GEN-LAST:event_txtCourseNameFocusLost

    private void txtCourseDescFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCourseDescFocusGained
        // TODO add your handling code here:
         if(txtCourseDesc.getText().equals("Course Description..."))
        {
            txtCourseDesc.setText("");
        }
    }//GEN-LAST:event_txtCourseDescFocusGained

    private void txtCourseDescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCourseDescFocusLost
        // TODO add your handling code here:
        if(txtCourseDesc.getText().equals(""))
        {
            txtCourseDesc.setText("Course Description...");
        }
    }//GEN-LAST:event_txtCourseDescFocusLost

    private void txtDepIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepIdFocusGained
        // TODO add your handling code here:
         if(txtDepId.getText().equals("Departement ID...."))
        {
            txtDepId.setText("");
        }
    }//GEN-LAST:event_txtDepIdFocusGained

    private void txtDepIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepIdFocusLost
        // TODO add your handling code here:
         if(txtDepId.getText().equals(""))
        {
            txtDepId.setText("Departement ID....");
        }
         
    }//GEN-LAST:event_txtDepIdFocusLost

    private void txtDepNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepNameFocusGained
        // TODO add your handling code here:
          if(txtDepName.getText().equals("Departement Name...."))
        {
            txtDepName.setText("");
        }
    }//GEN-LAST:event_txtDepNameFocusGained

    private void txtDepNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepNameFocusLost
        // TODO add your handling code here:
         if(txtDepName.getText().equals(""))
        {
            txtDepName.setText("Departement Name....");
        }
         
    }//GEN-LAST:event_txtDepNameFocusLost

    private void txtDepNoOfficeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepNoOfficeFocusGained
        // TODO add your handling code here:
          if(txtDepNoOffice.getText().equals("Departement Office No....."))
        {
            txtDepNoOffice.setText("");
        }
    }//GEN-LAST:event_txtDepNoOfficeFocusGained

    private void txtDepNoOfficeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepNoOfficeFocusLost
        // TODO add your handling code here:
         if(txtDepNoOffice.getText().equals(""))
        {
            txtDepNoOffice.setText("Departement Office No.....");
        }
    }//GEN-LAST:event_txtDepNoOfficeFocusLost

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        // TODO add your handling code here:
        String id=txtCourseId.getText().toString();
        String name=txtCourseName.getText().toString();
        String credit =String.valueOf(boxCourseCredit.getSelectedItem());
        String type=String.valueOf(boxCourseType.getSelectedItem());
        String desc=txtCourseDesc.getText().toString();
        try{
            
            Course.insertCourse(id, name, credit, type, desc);
        }  catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        clearCourseControls();
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnAddDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepActionPerformed
        // TODO add your handling code here:
        String id=txtDepId.getText().toString();
        String name=txtDepName.getText().toString();
        String num=txtDepNoOffice.getText().toString();
        try {
            
            Departement.insertDepartement(id, name, num);
            
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        clearDepControls();
    }//GEN-LAST:event_btnAddDepActionPerformed

    private void logOutAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutAdminActionPerformed
        // TODO add your handling code here:
        new LoginFrame().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_logOutAdminActionPerformed
    public void clearCourseControls()
        {
               txtCourseId.setText("");
               txtCourseName.setText("");
               txtCourseDesc.setText("");
            
        }
    public void clearDepControls()
    {
        txtDepId.setText("");
        txtDepName.setText("");
        txtDepNoOffice.setText("");
    }
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCourseCredit;
    private javax.swing.JComboBox<String> boxCourseType;
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnAddDep;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logOutAdmin;
    private javax.swing.JTextField txtCourseDesc;
    private javax.swing.JTextField txtCourseId;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtDepId;
    private javax.swing.JTextField txtDepName;
    private javax.swing.JTextField txtDepNoOffice;
    // End of variables declaration//GEN-END:variables
}
