/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package faculty.project;
import DB.Doctor;
import java.sql.Date;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author mohamed
 */
public class SignUpDoctors extends javax.swing.JFrame {

    /**
     * Creates new form SignUpDoctors
     */
    public SignUpDoctors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnSignInDoc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdDoc = new javax.swing.JTextField();
        txtPassDoc = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLNameDoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFNameDoc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMailDoc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnSignUpDoc = new javax.swing.JButton();
        txtDepId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPosDoc = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        docDate = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/headTh.png"))); // NOI18N

        btnSignInDoc.setBackground(new java.awt.Color(255, 255, 255));
        btnSignInDoc.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
        btnSignInDoc.setForeground(new java.awt.Color(204, 0, 0));
        btnSignInDoc.setText("SIGN IN");
        btnSignInDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnSignInDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSignInDoc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Sitka Heading", 1, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("   Create Account");

        txtIdDoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIdDoc.setForeground(new java.awt.Color(153, 153, 153));
        txtIdDoc.setText("Enter ID....");
        txtIdDoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtIdDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdDocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdDocFocusLost(evt);
            }
        });

        txtPassDoc.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txtPassDoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtPassDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassDocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassDocFocusLost(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Enter Password....");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user2.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock.png"))); // NOI18N

        txtLNameDoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLNameDoc.setForeground(new java.awt.Color(153, 153, 153));
        txtLNameDoc.setText("Enter Last Name....");
        txtLNameDoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtLNameDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLNameDocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLNameDocFocusLost(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id.png"))); // NOI18N

        txtFNameDoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFNameDoc.setForeground(new java.awt.Color(153, 153, 153));
        txtFNameDoc.setText("Enter First Name....");
        txtFNameDoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtFNameDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFNameDocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFNameDocFocusLost(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user2.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mail.png"))); // NOI18N

        txtMailDoc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMailDoc.setForeground(new java.awt.Color(153, 153, 153));
        txtMailDoc.setText("Enter E-mail....");
        txtMailDoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMailDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMailDocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMailDocFocusLost(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pos.png"))); // NOI18N

        btnSignUpDoc.setBackground(new java.awt.Color(204, 0, 0));
        btnSignUpDoc.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        btnSignUpDoc.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUpDoc.setText("SignUP");
        btnSignUpDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpDocActionPerformed(evt);
            }
        });

        txtDepId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDepId.setForeground(new java.awt.Color(153, 153, 153));
        txtDepId.setText("Enter Departement ID....");
        txtDepId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtDepId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepIdFocusLost(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/id.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Select Date....");

        txtPosDoc.setFont(new java.awt.Font("Segoe UI Light", 0, 20)); // NOI18N
        txtPosDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Docotor", "Admin", " " }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Select Position....");

        docDate.setDateFormatString("yyyy-MM-dd ");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(26, 26, 26))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(txtFNameDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                                .addComponent(txtLNameDoc)
                                .addComponent(txtMailDoc)
                                .addComponent(txtPassDoc)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtPosDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(docDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtIdDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepId, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnSignUpDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDepId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPassDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFNameDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(29, 29, 29)
                                .addComponent(txtLNameDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addComponent(txtMailDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPosDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(docDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(51, 51, 51)
                .addComponent(btnSignUpDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdDocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdDocFocusGained
        // TODO add your handling code here:
        if(txtIdDoc.getText().equals("Enter ID...."))
        {
            txtIdDoc.setText("");
        }
    }//GEN-LAST:event_txtIdDocFocusGained

    private void txtIdDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdDocFocusLost
        // TODO add your handling code here:
        if(txtIdDoc.getText().equals(""))
        {
            txtIdDoc.setText("Enter ID....");
        }
    }//GEN-LAST:event_txtIdDocFocusLost

    private void txtPassDocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassDocFocusGained
        // TODO add your handling code here:
        jLabel1.setVisible(false);

    }//GEN-LAST:event_txtPassDocFocusGained

    private void txtPassDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassDocFocusLost
        // TODO add your handling code here:
        if(txtPassDoc.getText().equals(""))
        {
            jLabel1.setVisible(true);
        }
    }//GEN-LAST:event_txtPassDocFocusLost

    private void txtLNameDocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLNameDocFocusGained
        // TODO add your handling code here:
        if(txtLNameDoc.getText().equals("Enter Last Name...."))
        {
            txtLNameDoc.setText("");
        }
    }//GEN-LAST:event_txtLNameDocFocusGained

    private void txtLNameDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLNameDocFocusLost
        // TODO add your handling code here:
        if(txtLNameDoc.getText().equals(""))
        {
            txtLNameDoc.setText("Enter Last Name....");
        }
    }//GEN-LAST:event_txtLNameDocFocusLost

    private void txtFNameDocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFNameDocFocusGained
        // TODO add your handling code here:
        if(txtFNameDoc.getText().equals("Enter First Name...."))
        {
            txtFNameDoc.setText("");
        }

    }//GEN-LAST:event_txtFNameDocFocusGained

    private void txtFNameDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFNameDocFocusLost
        // TODO add your handling code here:
        if(txtFNameDoc.getText().equals(""))
        {
            txtFNameDoc.setText("Enter First Name....");
        }
    }//GEN-LAST:event_txtFNameDocFocusLost

    private void btnSignUpDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpDocActionPerformed
        // TODO add your handling code here:
        
        String id=txtIdDoc.getText().toString();
        String depId=txtDepId.getText().toString();
        String fName=txtFNameDoc.getText().toString();
        String lName=txtLNameDoc.getText().toString();
        String position=String.valueOf(txtPosDoc.getSelectedItem());
        String mail=txtMailDoc.getText().toString();
        String pass=txtPassDoc.getText().toString();
        String date=((JTextField)docDate.getDateEditor().getUiComponent()).getText();
        
        try{
            Doctor.insertDoctor(id, depId, fName, lName, position, mail, pass,date);
        }catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
        
        clearControls();        
    }//GEN-LAST:event_btnSignUpDocActionPerformed

    private void btnSignInDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInDocActionPerformed
        // TODO add your handling code here:
        
            new LoginFrame().setVisible(true);
            this.dispose();


    }//GEN-LAST:event_btnSignInDocActionPerformed

    private void txtDepIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepIdFocusGained
        // TODO add your handling code here:
        if(txtDepId.getText().equals("Enter Departement ID...."))
        {
            txtDepId.setText("");
        }
    }//GEN-LAST:event_txtDepIdFocusGained

    private void txtDepIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepIdFocusLost
        // TODO add your handling code here:
        if(txtDepId.getText().equals(""))
        {
            txtDepId.setText("Enter Departement ID....");
        }
    }//GEN-LAST:event_txtDepIdFocusLost

    private void txtMailDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailDocFocusLost
        // TODO add your handling code here:
        if(txtMailDoc.getText().equals(""))
        {
            txtMailDoc.setText("Enter E-mail....");
        }
    }//GEN-LAST:event_txtMailDocFocusLost

    private void txtMailDocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailDocFocusGained
        // TODO add your handling code here:
        if(txtMailDoc.getText().equals("Enter E-mail...."))
        {
            txtMailDoc.setText("");
        }
    }//GEN-LAST:event_txtMailDocFocusGained
  void clearControls()
  {
      txtIdDoc.setText("");
      txtPassDoc.setText("");
      txtLNameDoc.setText("");
      txtFNameDoc.setText("");
      txtMailDoc.setText("");
  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpDoctors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpDoctors().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignInDoc;
    private javax.swing.JButton btnSignUpDoc;
    private java.awt.Canvas canvas1;
    private com.toedter.calendar.JDateChooser docDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDepId;
    private javax.swing.JTextField txtFNameDoc;
    private javax.swing.JTextField txtIdDoc;
    private javax.swing.JTextField txtLNameDoc;
    private javax.swing.JTextField txtMailDoc;
    private javax.swing.JPasswordField txtPassDoc;
    private javax.swing.JComboBox<String> txtPosDoc;
    // End of variables declaration//GEN-END:variables
}


